// Valores aproximados por 100 g, adaptados da TACO/NEPA-Unicamp (4ª edição).
// Preparações e marcas variam; estes dados têm finalidade educativa.
export const tacoFoods = [
  ["Arroz branco cozido", 128, "Carboidratos", 2.5, 28.1, 0.2],
  ["Arroz integral cozido", 124, "Carboidratos", 2.6, 25.8, 1],
  ["Feijão carioca cozido", 76, "Carboidratos", 4.8, 13.6, 0.5],
  ["Feijão preto cozido", 77, "Carboidratos", 4.5, 14, 0.5],
  ["Lentilha cozida", 93, "Proteínas", 6.3, 16.3, 0.5],
  ["Grão-de-bico cozido", 164, "Proteínas", 8.9, 27.4, 2.6],
  ["Aveia em flocos", 394, "Carboidratos", 13.9, 66.6, 8.5],
  ["Cuscuz de milho cozido", 113, "Carboidratos", 2.2, 25.3, 0.7],
  ["Tapioca preparada", 151, "Carboidratos", 0.2, 36, 0],
  ["Pão francês", 300, "Carboidratos", 8, 58.6, 3.1],
  ["Pão integral", 253, "Carboidratos", 9.4, 49.9, 3.7],
  ["Macarrão cozido", 157, "Carboidratos", 5.8, 30.9, 0.9],
  ["Batata inglesa cozida", 52, "Carboidratos", 1.2, 11.9, 0],
  ["Batata-doce cozida", 77, "Carboidratos", 0.6, 18.4, 0.1],
  ["Mandioca cozida", 125, "Carboidratos", 0.6, 30.1, 0.3],
  ["Peito de frango grelhado", 159, "Proteínas", 32, 0, 2.5],
  ["Patinho grelhado", 219, "Proteínas", 35.9, 0, 7.3],
  ["Carne moída magra cozida", 212, "Proteínas", 26.7, 0, 10.9],
  ["Tilápia grelhada", 128, "Proteínas", 26, 0, 2.7],
  ["Sardinha assada", 164, "Proteínas", 32.2, 0, 3],
  ["Atum em conserva drenado", 166, "Proteínas", 26.2, 0, 6],
  ["Ovo inteiro cozido", 146, "Proteínas", 13.3, 0.6, 9.5],
  ["Clara de ovo cozida", 59, "Proteínas", 13.4, 0, 0.1],
  ["Leite integral", 61, "Complementos", 2.9, 4.5, 3.2],
  ["Leite desnatado", 35, "Complementos", 3.4, 4.9, 0.2],
  ["Iogurte natural", 51, "Complementos", 4.1, 1.9, 3],
  ["Queijo minas frescal", 264, "Proteínas", 17.4, 3.2, 20.2],
  ["Tofu", 64, "Proteínas", 6.6, 2.1, 4],
  ["Proteína de soja cozida", 141, "Proteínas", 16.6, 11.1, 4.8],
  ["Banana prata", 98, "Hortifruti", 1.3, 26, 0.1],
  ["Maçã com casca", 56, "Hortifruti", 0.3, 15.2, 0],
  ["Mamão formosa", 45, "Hortifruti", 0.8, 11.6, 0.1],
  ["Laranja pera", 37, "Hortifruti", 1, 8.9, 0.1],
  ["Manga", 72, "Hortifruti", 0.4, 19.4, 0.2],
  ["Melancia", 33, "Hortifruti", 0.9, 8.1, 0],
  ["Morango", 30, "Hortifruti", 0.9, 6.8, 0.3],
  ["Abacate", 96, "Hortifruti", 1.2, 6, 8.4],
  ["Tomate", 15, "Hortifruti", 1.1, 3.1, 0.2],
  ["Cenoura cozida", 30, "Hortifruti", 0.8, 6.7, 0.2],
  ["Abóbora cabotiá cozida", 48, "Hortifruti", 1.4, 10.8, 0.7],
  ["Brócolis cozido", 25, "Hortifruti", 2.1, 4.4, 0.5],
  ["Couve refogada", 90, "Hortifruti", 1.7, 8.7, 6.6],
  ["Amendoim torrado", 606, "Complementos", 22.5, 18.7, 54],
  ["Castanha-do-pará", 643, "Complementos", 14.5, 15.1, 63.5],
  ["Pasta de amendoim", 590, "Complementos", 25, 20, 50],
  ["Chia", 486, "Complementos", 16.5, 42.1, 30.7],
  ["Azeite de oliva", 884, "Complementos", 0, 0, 100],
];

const r = (name, type, goals, kcal, protein, time, ingredients, steps, diets = ["Sem preferência"]) => ({
  name, type, goals, kcal, protein, time, ingredients, steps, diets,
});

export const recipeLibrary = [
  r("Omelete de legumes", "Café da manhã", ["Emagrecer", "Recomposição"], 285, 24, 12, ["2 ovos + 2 claras", "tomate", "cenoura", "1 fatia de pão integral"], ["Refogue os legumes.", "Junte os ovos batidos e cozinhe.", "Sirva com o pão."], ["Sem preferência", "Vegetariana"]),
  r("Cuscuz com ovos e tomate", "Café da manhã", ["Emagrecer", "Ganhar massa", "Recomposição"], 340, 20, 15, ["120 g de cuscuz cozido", "2 ovos", "tomate", "ervas"], ["Hidrate e cozinhe o cuscuz.", "Prepare os ovos com tomate.", "Monte o prato."], ["Sem preferência", "Vegetariana"]),
  r("Iogurte com banana e aveia", "Café da manhã", ["Emagrecer", "Recomposição"], 310, 17, 5, ["170 g de iogurte natural", "1 banana", "30 g de aveia", "canela"], ["Corte a banana.", "Misture tudo e finalize com canela."], ["Sem preferência", "Vegetariana"]),
  r("Panqueca de banana e aveia", "Café da manhã", ["Emagrecer", "Ganhar massa"], 355, 21, 12, ["1 banana", "2 ovos", "30 g de aveia", "canela"], ["Amasse e misture os ingredientes.", "Doure dos dois lados em frigideira."], ["Sem preferência", "Vegetariana"]),
  r("Tofu mexido com cuscuz", "Café da manhã", ["Emagrecer", "Recomposição"], 315, 19, 15, ["150 g de tofu", "100 g de cuscuz", "tomate", "cúrcuma"], ["Doure o tofu esfarelado com temperos.", "Sirva com o cuscuz."], ["Vegana", "Vegetariana"]),
  r("Vitamina proteica de banana", "Café da manhã", ["Ganhar massa", "Recomposição"], 430, 25, 5, ["250 ml de leite", "1 banana", "40 g de aveia", "15 g de pasta de amendoim"], ["Bata tudo até ficar cremoso."], ["Sem preferência", "Vegetariana"]),
  r("Prato brasileiro equilibrado", "Almoço", ["Emagrecer", "Recomposição"], 510, 43, 25, ["100 g de arroz", "100 g de feijão", "120 g de frango", "salada variada"], ["Grelhe o frango.", "Monte metade do prato com vegetais e complete com arroz e feijão." ]),
  r("Frango, batata-doce e brócolis", "Almoço", ["Emagrecer", "Ganhar massa", "Recomposição"], 485, 45, 30, ["140 g de frango", "180 g de batata-doce", "brócolis", "1 colher de chá de azeite"], ["Grelhe o frango.", "Cozinhe a batata e o brócolis.", "Finalize com azeite." ]),
  r("Patinho com arroz, feijão e couve", "Almoço", ["Ganhar massa", "Recomposição"], 610, 48, 30, ["120 g de patinho", "120 g de arroz", "100 g de feijão", "couve"], ["Grelhe a carne.", "Refogue a couve.", "Sirva com arroz e feijão." ]),
  r("Tilápia com purê de abóbora", "Almoço", ["Emagrecer", "Recomposição"], 420, 39, 30, ["150 g de tilápia", "250 g de abóbora", "salada", "azeite"], ["Grelhe a tilápia.", "Amasse a abóbora cozida e tempere.", "Sirva com salada." ]),
  r("Sardinha com arroz e feijão", "Almoço", ["Emagrecer", "Ganhar massa"], 560, 45, 25, ["130 g de sardinha", "120 g de arroz", "100 g de feijão", "tomate"], ["Asse a sardinha com temperos.", "Sirva com arroz, feijão e tomate." ]),
  r("Carne moída com mandioca", "Almoço", ["Ganhar massa"], 650, 42, 35, ["140 g de carne moída magra", "220 g de mandioca", "cenoura", "tomate"], ["Cozinhe a mandioca.", "Refogue a carne com os legumes.", "Sirva junto." ]),
  r("Bowl de lentilha e legumes", "Almoço", ["Emagrecer", "Recomposição"], 440, 20, 25, ["160 g de lentilha", "100 g de arroz integral", "brócolis", "cenoura"], ["Cozinhe os grãos.", "Salteie os legumes e monte o bowl."], ["Vegana", "Vegetariana"]),
  r("Grão-de-bico com abóbora", "Almoço", ["Emagrecer", "Recomposição"], 455, 18, 30, ["170 g de grão-de-bico", "200 g de abóbora", "couve", "tomate"], ["Asse a abóbora.", "Tempere o grão-de-bico.", "Sirva com couve e tomate."], ["Vegana", "Vegetariana"]),
  r("Macarrão com proteína de soja", "Almoço", ["Ganhar massa"], 620, 35, 30, ["180 g de macarrão", "120 g de proteína de soja", "molho de tomate", "legumes"], ["Cozinhe o macarrão.", "Refogue a soja com o molho e misture."], ["Vegana", "Vegetariana"]),
  r("Sanduíche de frango", "Lanche", ["Emagrecer", "Recomposição"], 330, 30, 10, ["2 fatias de pão integral", "90 g de frango desfiado", "tomate", "folhas"], ["Misture o frango com temperos.", "Monte com tomate e folhas." ]),
  r("Tapioca de atum", "Lanche", ["Emagrecer", "Recomposição"], 315, 27, 10, ["60 g de goma de tapioca", "90 g de atum", "tomate"], ["Prepare a tapioca.", "Recheie com atum e tomate." ]),
  r("Iogurte, mamão e chia", "Lanche", ["Emagrecer"], 220, 12, 5, ["170 g de iogurte", "150 g de mamão", "10 g de chia"], ["Misture e sirva gelado."], ["Sem preferência", "Vegetariana"]),
  r("Ovos cozidos com fruta", "Lanche", ["Emagrecer", "Recomposição"], 245, 14, 10, ["2 ovos", "1 maçã ou laranja"], ["Cozinhe os ovos por 9 a 10 minutos.", "Sirva com a fruta."], ["Sem preferência", "Vegetariana"]),
  r("Homus com cenoura e pão", "Lanche", ["Emagrecer", "Recomposição"], 295, 11, 12, ["80 g de homus", "cenoura em palitos", "1 fatia de pão integral"], ["Bata grão-de-bico cozido com limão e temperos.", "Sirva com cenoura e pão."], ["Vegana", "Vegetariana"]),
  r("Banana com pasta de amendoim", "Lanche", ["Ganhar massa"], 300, 8, 2, ["1 banana", "25 g de pasta de amendoim", "20 g de aveia"], ["Fatie a banana e cubra com os demais ingredientes."], ["Vegana", "Vegetariana"]),
  r("Frango com legumes na frigideira", "Jantar", ["Emagrecer", "Recomposição"], 390, 43, 20, ["140 g de frango", "brócolis", "cenoura", "100 g de batata"], ["Doure o frango em cubos.", "Junte os legumes e cozinhe até ficarem macios." ]),
  r("Sopa de frango e legumes", "Jantar", ["Emagrecer"], 345, 34, 35, ["120 g de frango", "batata", "abóbora", "cenoura", "couve"], ["Cozinhe tudo com temperos.", "Desfie o frango e devolva à panela." ]),
  r("Omelete reforçada com arroz", "Jantar", ["Emagrecer", "Ganhar massa"], 440, 29, 15, ["3 ovos", "100 g de arroz", "tomate", "couve"], ["Prepare a omelete com os vegetais.", "Sirva com arroz."], ["Sem preferência", "Vegetariana"]),
  r("Peixe assado com batata", "Jantar", ["Emagrecer", "Recomposição"], 430, 40, 35, ["160 g de peixe", "200 g de batata", "tomate", "cebola"], ["Asse tudo em uma travessa até dourar." ]),
  r("Escondidinho leve de carne", "Jantar", ["Ganhar massa", "Recomposição"], 570, 41, 40, ["150 g de carne moída", "250 g de abóbora ou batata", "tomate"], ["Refogue a carne.", "Cubra com o purê e leve ao forno para dourar." ]),
  r("Sopa de lentilha", "Jantar", ["Emagrecer"], 360, 20, 35, ["180 g de lentilha", "cenoura", "tomate", "couve"], ["Cozinhe tudo até engrossar e ajuste os temperos."], ["Vegana", "Vegetariana"]),
  r("Tofu xadrez com arroz", "Jantar", ["Emagrecer", "Recomposição"], 420, 22, 25, ["180 g de tofu", "100 g de arroz", "pimentão", "cenoura"], ["Doure o tofu.", "Junte os legumes e sirva com arroz."], ["Vegana", "Vegetariana"]),
  r("Hambúrguer de lentilha", "Jantar", ["Emagrecer", "Recomposição"], 410, 21, 35, ["160 g de lentilha", "30 g de aveia", "salada", "batata assada"], ["Amasse lentilha e aveia.", "Modele e doure.", "Sirva com salada e batata."], ["Vegana", "Vegetariana"]),
  r("Arroz, feijão e tofu grelhado", "Jantar", ["Ganhar massa", "Recomposição"], 540, 28, 25, ["120 g de arroz", "120 g de feijão", "180 g de tofu", "salada"], ["Grelhe o tofu com temperos.", "Sirva com arroz, feijão e salada."], ["Vegana", "Vegetariana"]),
  r("Creme de mamão com iogurte", "Ceia", ["Emagrecer"], 175, 10, 5, ["150 g de mamão", "120 g de iogurte", "canela"], ["Bata ou misture e sirva gelado."], ["Sem preferência", "Vegetariana"]),
  r("Leite com aveia e canela", "Ceia", ["Ganhar massa"], 260, 13, 5, ["250 ml de leite", "30 g de aveia", "canela"], ["Aqueça o leite e misture os demais ingredientes."], ["Sem preferência", "Vegetariana"]),
  r("Maçã assada com canela", "Ceia", ["Emagrecer"], 145, 3, 15, ["1 maçã", "10 g de aveia", "canela"], ["Asse a maçã com canela e finalize com aveia."], ["Vegana", "Vegetariana"]),
  r("Mousse rápida de banana e cacau", "Ceia", ["Emagrecer", "Recomposição"], 190, 5, 5, ["1 banana congelada", "cacau em pó", "10 g de chia"], ["Bata tudo até ficar cremoso."], ["Vegana", "Vegetariana"]),
];

export function recipesFor(data) {
  const diet = data.diet || "Sem preferência";
  return recipeLibrary.filter((recipe) =>
    recipe.goals.includes(data.goal || "Emagrecer") &&
    (diet === "Sem preferência" || recipe.diets.includes(diet)),
  );
}
